version: '3'

tasks:
  init:
    desc: Initialize the workspace
    cmds:
      - npm install
      - cp .env.example .env
      - cp .env.example .env.development
      - cp .env.example .env.production
  dev:
    desc: Start both apps in development mode
    cmds:
      - echo "Starting API..."
      - echo "Starting Admin UI..."
      - npm run dev
    env:
      NODE_ENV: 'development'
  build:
    desc: Build both apps (api and admin-ui)
    cmds:
      - echo "Building API..."
      - nx build api --prod
      - cd apps/admin-ui && npx vite build
    silent: false

  prod:
    desc: Run both apps in production mode
    cmds:
      - echo "Starting API..."
      - npm run dist/apps/api/main.js
      - echo "Starting Admin UI..."
